# DSO 545 Project Data Scraping

In [10]:
from sportsipy.nba.schedule import Schedule 
import pandas as pd

In [3]:
warriors_schedule = Schedule('GSW', year = '2015')

In [4]:
warriors_schedule[80].boxscore_index

'201504130GSW'

In [41]:
memphis_schedule = Schedule('LAL', year = '20')
memphis_schedule.dataframe.opponent_name.unique()

array(['Los Angeles Clippers', 'Dallas Mavericks', 'Atlanta Hawks',
       'Oklahoma City Thunder', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Hornets', 'Phoenix Suns', 'Denver Nuggets',
       'Detroit Pistons', 'Chicago Bulls', 'New York Knicks',
       'Golden State Warriors', 'New Jersey Nets', 'Miami Heat',
       'Utah Jazz', 'Minnesota Timberwolves', 'Milwaukee Bucks',
       'Cleveland Cavaliers', 'Sacramento Kings',
       'Portland Trail Blazers', 'San Antonio Spurs', 'Orlando Magic',
       'Toronto Raptors', 'Washington Wizards', 'Indiana Pacers',
       'Philadelphia 76ers', 'Boston Celtics', 'Charlotte Bobcats'],
      dtype=object)

In [6]:
memphis_schedule[80].boxscore_index

'201504130GSW'

In [7]:
warriors_schedule.dataframe.head()

,boxscore_index,date,datetime,game,location,losses,opponent_abbr,opponent_name,playoffs,points_allowed,points_scored,result,streak,time,wins
201410290SAC,201410290SAC,"Wed, Oct 29, 2014",2014-10-29,1,Away,0,SAC,Sacramento Kings,False,77,95,Win,W 1,10:00p,1
201411010GSW,201411010GSW,"Sat, Nov 1, 2014",2014-11-01,2,Home,0,LAL,Los Angeles Lakers,False,104,127,Win,W 2,10:30p,2
201411020POR,201411020POR,"Sun, Nov 2, 2014",2014-11-02,3,Away,0,POR,Portland Trail Blazers,False,90,95,Win,W 3,9:00p,3
201411050GSW,201411050GSW,"Wed, Nov 5, 2014",2014-11-05,4,Home,0,LAC,Los Angeles Clippers,False,104,121,Win,W 4,10:30p,4
201411080HOU,201411080HOU,"Sat, Nov 8, 2014",2014-11-08,5,Away,0,HOU,Houston Rockets,False,87,98,Win,W 5,8:00p,5

In [11]:
from pykml import parser 

filename = 'team_location.kml'
with open(filename) as f: 
    folder = parser.parse(f).getroot().Document.Folder

plnm=[]
cordi=[]
for pm in folder.Placemark:
    plnm1=pm.name
    plcs1=pm.Point.coordinates
    plnm.append(plnm1.text)
    cordi.append(plcs1.text)
    
db=pd.DataFrame()
db['place_name']=plnm
db['cordinates']=cordi

def dump(obj):
    for attr in dir(obj):
        if hasattr( obj, attr ):
            print( "obj.%s = %s" % (attr, getattr(obj, attr)))
#the kml output plnm1 and plcs1 are objects actually which can be viewed using the dump function from [SO](https://blender.stackexchange.com/questions/1879/is-it-possible-to-dump-an-objects-properties-and-methods)

db['Longitude'], db['Latitude'],db['value'] = zip(*db['cordinates'].apply(lambda x: x.split(',', 2)))

db

,place_name,cordinates,Longitude,Latitude,value
0,Boston Celtics,"-71.062228,42.366303,0",-71.062228,42.366303,0
1,Brooklyn Nets,"-73.974689,40.68265,0",-73.974689,40.68265,0
2,New York Knicks,"-73.993611,40.750556,0",-73.993611,40.750556,0
3,Philadelphia 76ers,"-75.171944,39.901111,0",-75.171944,39.901111,0
4,Toronto Raptors,"-79.379167,43.643333,0",-79.379167,43.643333,0
5,Chicago Bulls,"-87.674167,41.880556,0",-87.674167,41.880556,0
6,Cleveland Cavaliers,"-81.688056,41.496389,0",-81.688056,41.496389,0
7,Detroit Pistons,"-83.245556,42.696944,0",-83.245556,42.696944,0
8,Indiana Pacers,"-86.155556,39.763889,0",-86.155556,39.763889,0
9,Milwaukee Bucks,"-87.916944,43.043611,0",-87.916944,43.043611,0
10,Atlanta Hawks,"-84.396389,33.757222,0",-84.396389,33.757222,0
11,Charlotte Hornets,"-80.839167,35.225,0",-80.839167,35.225,0
12,Miami Heat,"-80.188056,25.781389,0",-80.188056,25.781389,0
13,Orlando Magic,"-81.383611,28.539167,0",-81.383611,28.539167,0
14,Washington Wizards,"-77.020833,38.898056,0",-77.020833,38.898056,0
15,Denver Nuggets,"-105.0075,39.748611,0",-105.0075,39.748611,0
16,Minnesota Timberwolves,"-93.276111,44.979444,0",-93.276111,44.979444,0
17,Oklahoma City Thunder,"-97.515,35.463333,0",-97.515,35.463333,0
18,Portland Trail Blazers,"-122.666667,45.531667,0",-122.666667,45.531667,0
19,Utah Jazz,"-111.901111,40.768333,0",-111.901111,40.768333,0
20,Golden State Warriors,"-122.3875,37.768056,0",-122.3875,37.768056,0
21,Los Angeles Clippers,"-118.267222,34.043056,0",-118.267222,34.043056,0
22,Phoenix Suns,"-112.071389,33.445833,0",-112.071389,33.445833,0
23,Sacramento Kings,"-121.518056,38.649167,0",-121.518056,38.649167,0
24,Dallas Mavericks,"-96.810278,32.790556,0",-96.810278,32.790556,0
25,Houston Rockets,"-95.362222,29.750833,0",-95.362222,29.750833,0
26,Memphis Grizzlies,"-90.050556,35.138333,0",-90.050556,35.138333,0
27,New Orleans Pelicans,"-90.081944,29.948889,0",-90.081944,29.948889,0
28,San Antonio Spurs,"-98.4375,29.426944,0",-98.4375,29.426944,0

In [14]:
import requests 
from bs4 import BeautifulSoup

In [15]:
wikiurl = 'https://en.wikipedia.org/wiki/National_Basketball_Association#Teams'


table_class="wikitable sortable jquery-tablesorter"
response=requests.get(wikiurl)
print(response.status_code)

200

In [27]:
soup = BeautifulSoup(response.text, 'html.parser')
nbatable=soup.find('table',{'class':"wikitable"})

In [31]:
df = pd.read_html(str(nbatable))
df=pd.DataFrame(df[0])
df

,Division,Team,Location,Arena,Capacity,Coordinates,Founded,Joined,Unnamed: 8_level_0
,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference,Eastern Conference
0,Atlantic,Boston Celtics,"Boston, Massachusetts",TD Garden,18624,".mw-parser-output .geo-default,.mw-parser-outp...",1946,1946,NaN
1,Atlantic,Brooklyn Nets,"New York City, New York",Barclays Center,17732,40°40′58″N 73°58′29″W﻿ / ﻿40.68265°N 73.974689°W,1967*,1976,NaN
2,Atlantic,New York Knicks,"New York City, New York",Madison Square Garden,19812,40°45′02″N 73°59′37″W﻿ / ﻿40.750556°N 73.993611°W,1946,1946,NaN
3,Atlantic,Philadelphia 76ers,"Philadelphia, Pennsylvania",Wells Fargo Center,21600,39°54′04″N 75°10′19″W﻿ / ﻿39.901111°N 75.171944°W,1946*,1949,NaN
4,Atlantic,Toronto Raptors,"Toronto, Ontario",Scotiabank Arena,19800,43°38′36″N 79°22′45″W﻿ / ﻿43.643333°N 79.379167°W,1995,1995,NaN
5,Central,Chicago Bulls,"Chicago, Illinois",United Center,20917,41°52′50″N 87°40′27″W﻿ / ﻿41.880556°N 87.674167°W,1966,1966,NaN
6,Central,Cleveland Cavaliers,"Cleveland, Ohio",Rocket Mortgage FieldHouse,20562,41°29′47″N 81°41′17″W﻿ / ﻿41.496389°N 81.688056°W,1970,1970,NaN
7,Central,Detroit Pistons,"Detroit, Michigan",Little Caesars Arena,20491,42°41′49″N 83°14′44″W﻿ / ﻿42.696944°N 83.245556°W,1941*,1948,NaN
8,Central,Indiana Pacers,"Indianapolis, Indiana",Gainbridge Fieldhouse,17923,39°45′50″N 86°09′20″W﻿ / ﻿39.763889°N 86.155556°W,1967,1976,NaN
9,Central,Milwaukee Bucks,"Milwaukee, Wisconsin",Fiserv Forum,18717,43°02′37″N 87°55′01″W﻿ / ﻿43.043611°N 87.916944°W,1968,1968,NaN
10,Southeast,Atlanta Hawks,"Atlanta, Georgia",State Farm Arena,15711,33°45′26″N 84°23′47″W﻿ / ﻿33.757222°N 84.396389°W,1946*,1949,NaN
11,Southeast,Charlotte Hornets,"Charlotte, North Carolina",Spectrum Center,19077,35°13′30″N 80°50′21″W﻿ / ﻿35.225°N 80.839167°W,1988*,1988*,NaN
12,Southeast,Miami Heat,"Miami, Florida",FTX Arena,19600,25°46′53″N 80°11′17″W﻿ / ﻿25.781389°N 80.188056°W,1988,1988,NaN
13,Southeast,Orlando Magic,"Orlando, Florida",Amway Center,18846,28°32′21″N 81°23′01″W﻿ / ﻿28.539167°N 81.383611°W,1989,1989,NaN
14,Southeast,Washington Wizards,"Washington, D.C.",Capital One Arena,20356,38°53′53″N 77°01′15″W﻿ / ﻿38.898056°N 77.020833°W,1961*,1961*,NaN
15,Western Conference,Western Conference,Western Conference,Western Conference,Western Conference,Western Conference,Western Conference,Western Conference,Western Conference
16,Northwest,Denver Nuggets,"Denver, Colorado",Ball Arena,19520,39°44′55″N 105°00′27″W﻿ / ﻿39.748611°N 105.0075°W,1967,1976,NaN
17,Northwest,Minnesota Timberwolves,"Minneapolis, Minnesota",Target Center,19356,44°58′46″N 93°16′34″W﻿ / ﻿44.979444°N 93.276111°W,1989,1989,NaN
18,Northwest,Oklahoma City Thunder,"Oklahoma City, Oklahoma",Paycom Center,18203,35°27′48″N 97°30′54″W﻿ / ﻿35.463333°N 97.515°W,1967*,1967*,NaN
19,Northwest,Portland Trail Blazers,"Portland, Oregon",Moda Center,19441,45°31′54″N 122°40′00″W﻿ / ﻿45.531667°N 122.666...,1970,1970,NaN
20,Northwest,Utah Jazz,"Salt Lake City, Utah",Vivint Arena,19911,40°46′06″N 111°54′04″W﻿ / ﻿40.768333°N 111.901...,1974*,1974*,NaN
21,Pacific,Golden State Warriors,"San Francisco, California",Chase Center,18064,37°46′05″N 122°23′15″W﻿ / ﻿37.768056°N 122.3875°W,1946*,1946*,NaN
22,Pacific,Los Angeles Clippers,"Los Angeles, California",Staples Center,19060,34°02′35″N 118°16′02″W﻿ / ﻿34.043056°N 118.267...,1970*,1970*,NaN
23,Pacific,Los Angeles Lakers,"Los Angeles, California",Staples Center,18997,34°02′35″N 118°16′02″W﻿ / ﻿34.043056°N 118.267...,1947*,1948,NaN
24,Pacific,Phoenix Suns,"Phoenix, Arizona",Footprint Center,18055,33°26′45″N 112°04′17″W﻿ / ﻿33.445833°N 112.071...,1968,1968,NaN
25,Pacific,Sacramento Kings,"Sacramento, California",Golden 1 Center,17500,38°38′57″N 121°31′05″W﻿ / ﻿38.649167°N 121.518...,1923*,1948,NaN
26,Southwest,Dallas Mavericks,"Dallas, Texas",American Airlines Center,19200,32°47′26″N 96°48′37″W﻿ / ﻿32.790556°N 96.810278°W,1980,1980,NaN
27,Southwest,Houston Rockets,"Houston, Texas",Toyota Center,18055,29°45′03″N 95°21′44″W﻿ / ﻿29.750833°N 95.362222°W,1967*,1967*,NaN
28,Southwest,Memphis Grizzlies,"Memphis, Tennessee",FedExForum,18119,35°08′18″N 90°03′02″W﻿ / ﻿35.138333°N 90.050556°W,1995*,1995*,NaN
29,Southwest,New Orleans Pelicans,"New Orleans, Louisiana",Smoothie King Center,16867,29°56′56″N 90°04′55″W﻿ / ﻿29.948889°N 90.081944°W,2002*,2002*,NaN
30,Southwest,San Antonio Spurs,"San Antonio, Texas",AT&T Center,18418,29°25′37″N 98°26′15″W﻿ / ﻿29.426944°N 98.4375°W,1967*,1976,NaN